print("jak se jmenujes?")
jmeno=input("")
print('jake mas oblibene zvire?')
zvire=input('')
print('v jakem meste bydlis?')
mesto=input('')
print('random sloveso napis pls')
sloveso=input('')
print("nejake random prid jmeno delej zrmde")
pridjmeno=input('')
print('oblibene nebo random jidlo')
jidlo=input('')
print('')
print('bylo nebylo, zil byl jeden zachod v mekaci, ktery se jmenoval', jmeno)
import time
time.sleep(1)
print('...')
print('zajima te co bude dal?')
odpoved=input('')
if odpoved == "ne" :
    print ('tak si naser')
else :
    print ('hodnej tak pokracujeme')
    time.sleep(1)
    print('a zachod pod jmenem', jmeno, "uvidel pred sebou divne stvoreni...")
    time.sleep(0.5)
    print('rikali mu', zvire, ",ale zachod to nevedel. tak to zvire zacalo znenadani", sloveso)
    time.sleep(0.5)
    print('a jak to', zvire, "vylekalo zachod, tak ten zachod se stal", pridjmeno, "zachod jmenem", jmeno)
    time.sleep(1)
    print('... tebe to fakt zajima?')
    odpoved1=input('')
    if odpoved1 == "ne" :
        time.sleep(0.4)
        print('dobry uz nemusime dal s touhle picovinou')
    else:
        time.sleep(0.4)
        print("ehh ok tvoje vec...")
        time.sleep(0.5)
        print('pockej premyslim..')
        time.sleep(0.2)
        print('nemuzu vymyslet co dal..')
        time.sleep(0.2)
        print('...')
        time.sleep(6)
        print('uz to mam!')
        time.sleep(0.1)
        print('a kdyz se ze zachoda stalo toto, tak se vsichni dozvedeli, ze pochazi z mesta', mesto)
        time.sleep(0.2)
        print('a jeste personal uvidel, jak', pridjmeno, "zachod krade", jidlo, "u zakazniku, dokud oni cumi na skibidi dopdoopdop a sixseven!!!!")
        time.sleep(0.1)
        print('a proto jsou brainroty tak nebezpecne..')
        print('jinak napis ty jak by to mohlo pokracovat...')
        pokracovani=input('')
        print('hele, nevidim cos napsal, ale uz ted vim..')
        time.sleep(4)
        print('...ze to bude stat za hovno.')
        print('hezkej den papa')
